name: Get Citation Data

on:
  page_build:
  schedule:
    - cron:  '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Reqs
        run: |
          sudo apt-get install python3-setuptools
      - name: Run
        run: |
          cd ./google_scholar_crawler
          pip3 install -r requirements.txt
          python3 main.py
          cd ./results
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"  # 设置用户邮箱
          git add *.json
          git commit -m "Updated Citation Data" || echo "No changes to commit"
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:google-scholar-stats --force
        env:
          GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
